apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db  # Alinhado com o Service
  template:
    metadata:
      labels:
        app: db  # Alinhado com o Service
    spec:
      containers:
        # Container do PostgreSQL
        - name: postgress-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secrets          
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: ${{ secrets.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ${{ secrets.POSTGRES_DB }}
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ${{ secrets.POSTGRES_USER }}